name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: taiga-family/actions/setup-variables@5b954545ec33833478961976b2ce4fd3c6b89149 # v2.7.0
      - uses: taiga-family/actions/setup-node@5b954545ec33833478961976b2ce4fd3c6b89149 # v2.7.0
        with:
          audit: true

      - run: |
          if [[ "${{ env.SUPPORT_AUTO_PUSH }}" == "true" ]]; then
              npm run prettier -- --write
              npm run stylelint -- --fix
              npm run lint -- --fix
          else
              npm run prettier -- --check
              npm run stylelint
              npm run lint
          fi

      - run: npm run cspell
      - run: npm run build
      - run: npm run test

      - uses: taiga-family/actions/auto-push@5b954545ec33833478961976b2ce4fd3c6b89149 # v2.7.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
