name: Deploy demo
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: taiga-family/actions/setup-variables@399268333d80c132c3bf9939f33e4db8b7f11be5 # v2.11.0
      - uses: taiga-family/actions/setup-node@399268333d80c132c3bf9939f33e4db8b7f11be5 # v2.11.0
      - run: npm run build:demo
      - uses: taiga-family/actions/deploy-github-pages@399268333d80c132c3bf9939f33e4db8b7f11be5 # v2.11.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/apps/demo/browser

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
