name: Deploy demo
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: taiga-family/ci/actions/setup/variables@44fd3eb3c46e9e6c39fd3820479c467aa75c8028 # v1.221.0
      - uses: taiga-family/ci/actions/setup/node@44fd3eb3c46e9e6c39fd3820479c467aa75c8028 # v1.221.0
      - run: npm run build:demo
      - uses: taiga-family/ci/actions/deploy/github-pages@44fd3eb3c46e9e6c39fd3820479c467aa75c8028 # v1.221.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/apps/demo/browser

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
