name: Deploy demo
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: taiga-family/actions/setup-variables@a12b79beab3aea8bd840e48e902a2084d282e1a6 # v2.5.0
      - uses: taiga-family/actions/setup-node@a12b79beab3aea8bd840e48e902a2084d282e1a6 # v2.5.0
      - run: npm run build:demo
      - uses: taiga-family/actions/deploy-github-pages@a12b79beab3aea8bd840e48e902a2084d282e1a6 # v2.5.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/apps/demo/browser

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
